### ISSUE TITLE
pretrained module

### ISSUE THREAD

**Issue by twsha** [StuLiu/SOSNet#1]
hello ,do you hava resnet pretrained module

**Comment by StuLiu** [comment]
Hi! The backbones can be downloaded from the following site
https://github.com/sithu31296/semantic-segmentation/blob/main/docs/BACKBONES.md

**Comment by twsha** [comment]
> Hi! The backbones can be downloaded from the following site https://github.com/sithu31296/semantic-segmentation/blob/main/docs/BACKBONES.md

thank you
